---
title: "MUSA_Final"
author: "Richard Barad"
date: "2023-12-04"
output: html_document
---

```{r clear_environment, cache = TRUE, include = FALSE}

# Lists All Of The Objects In The Work Space
rm(list=ls())
```

```{r knitting_options, include = FALSE}
# Global Options For Knitting Chunks
knitr::opts_chunk$set(echo = T, messages = F, warning = F, error = F)
```

```{r import_libraries, include = FALSE}
library(tidyverse) # Data Science Workflow & Representation
library(tidycensus) # Load United States Census Boundary & Attribute Data
library(sf) # Standardized Way To Encode Spatial Vector Data
library(spdep) # Spatial Dependence: Weighting Schemes & Statistics
library(caret) # Classification and Regression Training
library(FNN) # Fast Nearest Neighbor Search Algorithms & Applications
library(RSocrata) # Download or Upload 'Socrata' Data Sets/Open Data Portals
library(viridis) # Colorblind-Friendly Color Maps Package
library(gridExtra) # Miscellaneous Functions for "Grid" Graphics
library(knitr) # General-Purpose Package for Dynamic Report Generation
library(kableExtra) # Construct Complex Table with 'Kable' and Pipe Syntax
library(plotROC) # Generate Useful ROC Curve Charts for Print and Interactive Use
library(pROC) # Display and Analyze Receiver Operating Characteristic Curves
library(lubridate) # Functions to Work with Date-Times and Time-Spans
library(ggpubr) # GGPLOT Based Publication Ready Plots
library(ggcorrplot) # Visualization of a Correlation Matrix Using GGPLOT2
```

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Read the data using the Socrata API

I filtered to just restaurants and converted data to an SF object

```{r read_data}

filter <- c("Restaurant","Bakery","TAVERN","ICE CREAM","ICE CREAM SHOP","GROCERY/DELI","GROCERY/RESTAURANT","RESTAURANT/BAR","RESTAURANT/GROCERY STORE","CAFE/STORE","Coffee shop","GAS STATION/RESTAURANT","GROCERY/TAQUERIA","Grocery & Restaurant","Grocery(Sushi prep)","HOT DOG STATION","JUICE AND SALAD BAR")

data <- read.socrata("https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5") %>%
  na.omit() %>%
  dplyr::filter(facility_type %in% filter) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
  mutate(inspection_date = ymd(inspection_date),
         year = year(inspection_date)) %>%
  st_transform('ESRI:102271')
```

## Read Neighboorhoods Data

```{r neighboorhoods_data}

neighboorhoods <- st_read('https://data.cityofchicago.org/api/geospatial/bbvz-uum9?method=export&format=GeoJSON')%>%
  st_transform('ESRI:102271') %>%
  dplyr::select(pri_neigh)

```
I figured our training data would be one year of data - this is 9,170 data points. I also removed all results which were not Pass or Fail.

```{r training_data}
data_2021 <- data %>%
  dplyr::filter(year == 2021 & results != 'Out of Business' & results != 'No Entry' & results != 'Not Ready') %>%
  mutate(results = ifelse(results=="Pass w/ Conditions","Pass",results)) %>%
  st_join(.,neighboorhoods,predicate = st_intersects) %>%
  mutate(pri_neigh = ifelse(location == "(42.008536400868735, -87.91442843927047)","O'Hare",pri_neigh),
         pri_neigh = ifelse(location %in% c("(41.892249163400116, -87.60951804879336)","(41.89233780863412, -87.6040447589981)"),"Streeterville",pri_neigh))
```

## Census Wrangling

```{r census_data}

```

## Including Plots

Quick Map 1

```{r guick_map}
ggplot()+
  geom_sf(data=neighboorhoods)+
  geom_sf(data=data_2021,aes(color=results),size=0.5)+
  theme_void()
```
```{r guick_map}
neigh_summ <- data_2021 %>% st_drop_geometry() %>%
  group_by(pri_neigh,results) %>% tally() %>%
  spread(key=results,value=n) %>%
  mutate(Fail = replace_na(Fail,0),
    pct_pass = Pass / (Fail + Pass) * 100,
    pct_fail = Fail / (Fail + Pass) * 100)%>%
  left_join(neighboorhoods,.,by='pri_neigh') 
  
ggplot()+
  geom_sf(data=neigh_summ,aes(fill=pct_pass))+
  scale_fill_viridis_c(option='rocket')+
  theme_void()
```
```{r guick_chart, fig.width=14}

neigh_summ %>% 
  st_drop_geometry() %>%
  select(pri_neigh,pct_pass,pct_fail) %>%
  gather(pass,rate,-pri_neigh) %>%
  na.omit() %>%
  ggplot(aes(x=pri_neigh,y=rate,fill=pass))+
  geom_bar(position='stack',stat='identity')+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# Alec's Code Begins Here

```{r chicago_boundary}

chicagoboundary <- 
  st_read("https://data.cityofchicago.org/api/geospatial/ewy2-6yfk?method=export&format=GeoJSON") %>%
  st_transform('ESRI:102271')

```

```{r sanitation_complaints}

sanitation <- st_read("https://data.cityofchicago.org/resource/rccf-5427.geojson") %>%
  st_transform('ESRI:102271') 

```

```{r complaints_visualized, fig.width=9.5, fig.height=4}

grid.arrange(ncol=2,
ggplot() + 
  geom_sf(data = chicagoboundary) +
  geom_sf(data = sanitation, colour="blue", size=0.1, show.legend = "point") +
  labs(title= "Sanitation Code Complaints"), 

ggplot() + 
  geom_sf(data = chicagoboundary, fill = "grey80") +
  stat_density2d(data = data.frame(st_coordinates(st_centroid(sanitation))), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_viridis() +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "Density of Sanitation Code Complaints") +
  theme(legend.position = "none"))
```

```{r rodent_baiting}

rodent <- st_read("https://data.cityofchicago.org/resource/uqhs-j723.geojson")%>%
  st_transform('ESRI:102271') 

```

```{r baiting_visualized, fig.width=9.5, fig.height=4}
grid.arrange(ncol=2,
ggplot() + 
  geom_sf(data = chicagoboundary) +
  geom_sf(data = rodent, colour="blue", size=0.1, show.legend = "point") +
  labs(title= "Rodent Baiting"),

ggplot() + 
  geom_sf(data = chicagoboundary, fill = "grey80") +
  stat_density2d(data = data.frame(st_coordinates(st_centroid(rodent))), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.01, bins = 40, geom = 'polygon') +
  scale_fill_viridis() +
  scale_alpha(range = c(0.00, 0.35), guide = FALSE) +
  labs(title = "Density of Rodent Baiting") + 
  theme(legend.position = "none"))
```
